မင်္ဂလာပါ၊ Data Science Using Python - Week 06 က ကြိုဆိုပါတယ်။ 

ဒီအပါတ်မှာ 

* Programming (Python) Refresher
* Introduction to Numpy နဲ့ 
* Introduction to Scipy တို့ကို ဆွေးနွေးမှာ ဖြစ်တယ်။ 

# Programming (Python) Refresher

## Python Data Types 

### Primitive Data Types

There are 4 primitive data types in python. They are : 

* int
* float
* str and
* bool

### Non-primitive Data Types

Primary non-primitive data types include: 

* list
* dict and 
* tuple

Primitive data types and tuples can be **hashed** or **indexed**. Therefore they can be a dictionary's keys. `list` and `dict` can't be indexed. 

```python
t = ("I", "am", "a", "hashable", "tuple")
l = ["I", "am", "a", "list"]
d = {
    "k1" : "value_1",
    2: "value_2",
    (1, 2): {
        "a": "b"
    }
}
```

#### `list` and `dict` Comprehension

```python
fruits = ["lemon", "grape", "orange", "papaya", "banana"]
prices = [10, 20.0, 10.50, 40, "sold out"]

# this is dict comprehension
fruit_2_price = {f: p for f, p in zip (fruits, prices)}

# these are list comprehension
sour_fruits = [f for f in fruits if f in ["lemon", "grape", "orange"]]
available_prices = [p for p in prices if p != "sold out"]
```


## Control Flow

### Sequential

Python program executes one statement after another in top to bottom fashion.

### Conditional

A simple if

```python
a = input("want to quit ? [Y/N] : ")
a = a.upper()
if a == 'Y':
    exit()
```

An if/else structure

```python
a = input("want to quit ? [Y/N] : ")
a = a.upper()
if a == 'Y':
    exit()
else:
    do_something()
```

An if/elif/else structure

```python
c = input("[R]ock/[P]aper/[S]cissor ? :")
c = c.upper()
if c == 'R':
    print ("you choose Rock")
elif c == 'P':
    print ("you choose Paper")
elif c == 'S':
    print ("you choose Scissor")
else:
    print ("invalid selection)
```

### Loop

There are two kinds of loops in python

#### For

```python
for f in ["lemon", "grape", "apple"]:
    print (f)
```

#### While

```python
while True:
    do_something()
    a = ""
    while a not in ["Y", "N"]:
        a = input("continue [Y/N] ? : ")
        a = a.upper()
    if a == "N":
        break
```

## Assignment 1

Given a 5 x 5 matrices A and B, calculate A + B.

In [ ]:
A = [
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
]
B = [
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
]
# calculate A + B here

## Functions

### Declaration

```python
def function_name(a, b):
    if isinstance(a, int) and isinstance(b, int):
        return a + b
    else:
        sum = 0
        for i in range(0, 5):
            sum = sum + a * b
        return sum
```

### Invokation

```python
x = function_name(1, 4) # x will be 5
y = function_name(2.0, 3.0) # y will be 30
```

### Notable Functions

#### `range`

```python
# this will print 0, 2, ... 98
for i in range(0, 100, 2):
    print (i) 
```

#### `zip`

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
c = ["a", "b", "c", "d", "e"]

# this will print
# a : 11
# b : 22
# ...
# e : 55
for cc, aa, bb in zip (c, a, b):
    print ("{} : {}".format(cc, aa+bb))
```

#### `enumerate`

```python
my_list = ["a", "b", "c"]
# this will print 
# 1 : a
# 2 : b
# 3 : c
for idx, itm in enumerate(my_list):
    print ("{} : {}".format(idx, itm))
```

## Python Project Structure

```python
# my_package/my_module.py

element=10
some_data={
    1 : [1, 2, 3],
    2 : {
        "a": "b",
        "c": "d"
    }
}
def my_function(a, b):
    return a + b
```

```python
# my_package/__main__.py
from io import StringIO

import numpy as np

from my_package.my_module import element, some_data, my_function

if __name__ == "__main__":
    print (element)
    print (some_data)
    print (my_function(1, 2))
```

# Introduction to `numpy`

In [ ]:
import numpy as np
A = np.array([
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4]
] )
B = np.array([
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8],
    [8, 1, 9, 2, 8]
])

In [6]:
C = A + B
print (C)

[[ 8  2 11  5 12]
 [ 8  2 11  5 12]
 [ 8  2 11  5 12]
 [ 8  2 11  5 12]
 [ 8  2 11  5 12]]


**Wow!!! So EASY**